### ISSUE TITLE
Hello, there is a problem with the deployment of vercel. Please help.

### ISSUE THREAD

**Issue by whois-ls** [aelew/lookup.tools#31]
Hello, after I have finished installing with vercel, the query functions such as IP, whois, mailbox and so on cannot be used.

The following error occurred in querying IP
Domain not found
Looks like the domain whois.com hasn't been registered yet.

The following error occurred in querying the domain name

An unexpected error occurred.
Error code: unauthorized

**Comment by whois-ls** [comment]
我部署的网站域名是，whois.ls

**Comment by aelew** [comment]
see #24
